# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest
  
steps:
- script: |
    curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 -o /usr/bin/clair-scanner
      chmod +x /usr/bin/clair-scanner
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      docker pull nginx
      clair-scanner --ip="localhost" nginx
